/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import databasecontrol.DatabaseConnection;
import databasecontrol.StudentManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.Student;
import models.StudentsTable;

/**
 *
 * @author julio
 */
public class EmployeeAddStudent extends javax.swing.JFrame {

    DatabaseConnection connection = new DatabaseConnection();
    StudentManager sm = new StudentManager();
    Student st = new Student();
    int flag = 0;
    
    public EmployeeAddStudent() {
        initComponents();
        FillStudentTable("SELECT *FROM students ORDER BY name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameCoursesAdd = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudents = new javax.swing.JTable();
        jFormattedTextFieldStudentSearch = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabelStudentName = new javax.swing.JLabel();
        jFormattedTextFieldStudentName = new javax.swing.JFormattedTextField();
        jLabelStudentPassport = new javax.swing.JLabel();
        jFormattedTextFieldStudentPass = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldStudentPhone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldStudentNatio = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldStudentAddress = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldStudentId = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldStudentPassword = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldCourseID = new javax.swing.JFormattedTextField();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonSaveStudent = new javax.swing.JButton();
        jButtonCancelStudent = new javax.swing.JButton();
        jButtonEditStudent = new javax.swing.JButton();
        jButtonDeleteStudent = new javax.swing.JButton();
        jButtonManageLecturers = new javax.swing.JButton();
        jButtonManageStudents = new javax.swing.JButton();
        jButtonManageCourses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameCoursesAdd.setMaximizable(true);
        jInternalFrameCoursesAdd.setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStudents);

        jFormattedTextFieldStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldStudentSearchActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelStudentName.setText("Name");

        jFormattedTextFieldStudentName.setEnabled(false);

        jLabelStudentPassport.setText("Passport");

        jFormattedTextFieldStudentPass.setEnabled(false);

        jLabel1.setText("Phone");

        jFormattedTextFieldStudentPhone.setEnabled(false);

        jLabel2.setText("Nationality");

        jFormattedTextFieldStudentNatio.setEnabled(false);

        jLabel3.setText("Address");

        jFormattedTextFieldStudentAddress.setEnabled(false);

        jLabel4.setText("ID");

        jFormattedTextFieldStudentId.setEnabled(false);

        jLabel5.setText("Password");

        jFormattedTextFieldStudentPassword.setEnabled(false);

        jLabel6.setText("CourseID");

        jFormattedTextFieldCourseID.setEnabled(false);
        jFormattedTextFieldCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCourseIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCourseID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelStudentPassport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldStudentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldStudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelStudentName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldStudentNatio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldStudentAddress)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldStudentSearch)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStudentName)
                    .addComponent(jFormattedTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldStudentNatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldStudentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStudentPassport)
                    .addComponent(jFormattedTextFieldStudentPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldStudentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jFormattedTextFieldStudentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jButtonAddStudent.setText("Add");
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });

        jButtonSaveStudent.setText("Save");
        jButtonSaveStudent.setEnabled(false);
        jButtonSaveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveStudentActionPerformed(evt);
            }
        });

        jButtonCancelStudent.setText("Cancel");
        jButtonCancelStudent.setEnabled(false);
        jButtonCancelStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelStudentActionPerformed(evt);
            }
        });

        jButtonEditStudent.setText("Edit");
        jButtonEditStudent.setEnabled(false);
        jButtonEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStudentActionPerformed(evt);
            }
        });

        jButtonDeleteStudent.setText("Delete");
        jButtonDeleteStudent.setEnabled(false);
        jButtonDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCoursesAddLayout = new javax.swing.GroupLayout(jInternalFrameCoursesAdd.getContentPane());
        jInternalFrameCoursesAdd.getContentPane().setLayout(jInternalFrameCoursesAddLayout);
        jInternalFrameCoursesAddLayout.setHorizontalGroup(
            jInternalFrameCoursesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCoursesAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCoursesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSaveStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jInternalFrameCoursesAddLayout.setVerticalGroup(
            jInternalFrameCoursesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCoursesAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCoursesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrameCoursesAddLayout.createSequentialGroup()
                        .addComponent(jButtonAddStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaveStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteStudent)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jInternalFrameCoursesAdd);
        jInternalFrameCoursesAdd.setBounds(160, 60, 560, 370);

        jButtonManageLecturers.setText("Manage Lecturers");
        jButtonManageLecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageLecturersActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonManageLecturers);
        jButtonManageLecturers.setBounds(20, 400, 130, 22);

        jButtonManageStudents.setText("Manage Students");
        jButtonManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonManageStudents);
        jButtonManageStudents.setBounds(20, 280, 130, 22);

        jButtonManageCourses.setText("Manage Courses");
        jButtonManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCoursesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonManageCourses);
        jButtonManageCourses.setBounds(20, 170, 130, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgemployeemainstudent.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 730, 450);

        setSize(new java.awt.Dimension(739, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCoursesActionPerformed
        EmployeeAddCourse screen = new EmployeeAddCourse();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManageCoursesActionPerformed

    private void jTableStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentsMouseClicked
        String id = ""+jTableStudents.getValueAt(jTableStudents.getSelectedRow(), 0);
        connection.Connection();
        
        connection.ExecuteSQL("SELECT *FROM students WHERE id='"+id+"'");
        try {
            connection.rs.first();
            jFormattedTextFieldStudentId.setText(connection.rs.getString("id"));
            jFormattedTextFieldStudentName.setText(connection.rs.getString("name"));
            jFormattedTextFieldStudentNatio.setText(connection.rs.getString("nationality"));
            jFormattedTextFieldStudentAddress.setText(connection.rs.getString("address"));
            jFormattedTextFieldStudentPass.setText(connection.rs.getString("passport"));
            jFormattedTextFieldStudentPhone.setText(connection.rs.getString("phone"));
            jFormattedTextFieldStudentPassword.setText(connection.rs.getString("password"));
            jFormattedTextFieldCourseID.setText(connection.rs.getString("courseID"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Selection Error:\n" + ex.getMessage());
        }
        
        jButtonEditStudent.setEnabled(true);
        jButtonDeleteStudent.setEnabled(true);
        
        connection.Desconnect();
    }//GEN-LAST:event_jTableStudentsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        st.setSearch(jFormattedTextFieldStudentSearch.getText());
        Student stu = sm.SearchStudent(st);
        jFormattedTextFieldStudentId.setText(stu.getId());
        jFormattedTextFieldStudentName.setText(stu.getName());
        jFormattedTextFieldStudentNatio.setText(stu.getNationality());
        jFormattedTextFieldStudentAddress.setText(stu.getAddress());
        jFormattedTextFieldStudentPass.setText(stu.getPassport());
        jFormattedTextFieldStudentPhone.setText(stu.getPhone());
        jFormattedTextFieldStudentPassword.setText(stu.getPassword());
        jButtonEditStudent.setEnabled(true);
        jButtonDeleteStudent.setEnabled(true);
        jFormattedTextFieldStudentSearch.setEnabled(true);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        flag = 1;
        jFormattedTextFieldStudentName.setEnabled(true);
        jFormattedTextFieldStudentNatio.setEnabled(true);
        jFormattedTextFieldStudentAddress.setEnabled(true);
        jFormattedTextFieldStudentPass.setEnabled(true);
        jFormattedTextFieldStudentPhone.setEnabled(true);
        jFormattedTextFieldCourseID.setEnabled(true);
        jFormattedTextFieldStudentName.setText("");
        jFormattedTextFieldStudentNatio.setText("");
        jFormattedTextFieldStudentAddress.setText("");
        jFormattedTextFieldStudentPass.setText("");
        jFormattedTextFieldStudentPhone.setText("");
        jFormattedTextFieldCourseID.setText("");
        jButtonSaveStudent.setEnabled(true);
        jButtonCancelStudent.setEnabled(true);
        jButtonEditStudent.setEnabled(false);
        jButtonDeleteStudent.setEnabled(false);
        jFormattedTextFieldStudentSearch.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jButtonSaveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveStudentActionPerformed
        if (jFormattedTextFieldStudentName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name Required");
            jFormattedTextFieldStudentName.requestFocus();
        } else if (jFormattedTextFieldStudentNatio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nationality Required");
            jFormattedTextFieldStudentNatio.requestFocus();
        } else if (jFormattedTextFieldStudentAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Address Required");
            jFormattedTextFieldStudentAddress.requestFocus();
        } else if (jFormattedTextFieldStudentPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Passport Required");
            jFormattedTextFieldStudentPass.requestFocus();
        } else if (jFormattedTextFieldStudentPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Phone Required");
            jFormattedTextFieldStudentPhone.requestFocus();
        } else if (jFormattedTextFieldCourseID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course ID Required");
            jFormattedTextFieldCourseID.requestFocus();
        } else {
            if (flag==1) {
                st.setName(jFormattedTextFieldStudentName.getText());
                st.setNationality(jFormattedTextFieldStudentNatio.getText());
                st.setAddress(jFormattedTextFieldStudentAddress.getText());
                st.setPassport(jFormattedTextFieldStudentPass.getText());
                st.setPhone(jFormattedTextFieldStudentPhone.getText());
                st.setCourseID("VGC"+jFormattedTextFieldCourseID.getText());
                st.setId(st.createId());
                st.setPassword("12345");
                sm.SaveStudent(st);
                jFormattedTextFieldStudentName.setText("");
                jFormattedTextFieldStudentNatio.setText("");
                jFormattedTextFieldStudentAddress.setText("");
                jFormattedTextFieldStudentPass.setText("");
                jFormattedTextFieldStudentPhone.setText("");
                jFormattedTextFieldCourseID.setText("");
                jFormattedTextFieldStudentName.setEnabled(false);
                jFormattedTextFieldStudentNatio.setEnabled(false);
                jFormattedTextFieldStudentAddress.setEnabled(false);
                jFormattedTextFieldStudentPass.setEnabled(false);
                jFormattedTextFieldStudentPhone.setEnabled(false);
                jFormattedTextFieldCourseID.setEnabled(false);
                jFormattedTextFieldStudentSearch.setEnabled(true);
                jButton1.setEnabled(true);
                jButtonSaveStudent.setEnabled(false);
                jButtonCancelStudent.setEnabled(false);
                FillStudentTable("SELECT *FROM students ORDER BY name");
            }
            else {
                st.setId(jFormattedTextFieldStudentId.getText());
                st.setName(jFormattedTextFieldStudentName.getText());
                st.setNationality(jFormattedTextFieldStudentNatio.getText());
                st.setAddress(jFormattedTextFieldStudentAddress.getText());
                st.setPassport(jFormattedTextFieldStudentPassword.getText());
                st.setPhone(jFormattedTextFieldStudentPhone.getText());
                st.setPassword(jFormattedTextFieldStudentPassword.getText());
                st.setCourseID(jFormattedTextFieldCourseID.getText());
                sm.EditStudent(st);
                jFormattedTextFieldStudentName.setText("");
                jFormattedTextFieldStudentNatio.setText("");
                jFormattedTextFieldStudentAddress.setText("");
                jFormattedTextFieldStudentPass.setText("");
                jFormattedTextFieldStudentPhone.setText("");
                jFormattedTextFieldStudentId.setText("");
                jFormattedTextFieldStudentPassword.setText("");
                jFormattedTextFieldCourseID.setText("");
                jFormattedTextFieldStudentName.setEnabled(false);
                jFormattedTextFieldStudentAddress.setEnabled(false);
                jFormattedTextFieldStudentPass.setEnabled(false);
                jFormattedTextFieldStudentPhone.setEnabled(false);
                jFormattedTextFieldCourseID.setEnabled(false);
                jButtonSaveStudent.setEnabled(false);
                jButtonCancelStudent.setEnabled(false);
                jButtonAddStudent.setEnabled(true);
                FillStudentTable("SELECT *FROM students ORDER BY name");
            }
        }
    }//GEN-LAST:event_jButtonSaveStudentActionPerformed

    private void jButtonCancelStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelStudentActionPerformed
       jFormattedTextFieldStudentName.setEnabled(!true);
        jFormattedTextFieldStudentNatio.setEnabled(!true);
        jFormattedTextFieldStudentAddress.setEnabled(!true);
        jFormattedTextFieldStudentPass.setEnabled(!true);
        jFormattedTextFieldStudentPhone.setEnabled(!true);
        jFormattedTextFieldStudentPassword.setEnabled(!true);
        jFormattedTextFieldCourseID.setEnabled(!true);
        jButtonSaveStudent.setEnabled(!true);
        jButtonCancelStudent.setEnabled(!true);
        jButtonAddStudent.setEnabled(true);
        jButtonEditStudent.setEnabled(false);
        jButtonDeleteStudent.setEnabled(false);
        jFormattedTextFieldStudentName.setText("");
        jFormattedTextFieldStudentNatio.setText("");
        jFormattedTextFieldStudentAddress.setText("");
        jFormattedTextFieldStudentPass.setText("");
        jFormattedTextFieldStudentPhone.setText("");
        jFormattedTextFieldStudentId.setText("");
        jFormattedTextFieldStudentPassword.setText("");
        jFormattedTextFieldCourseID.setText("");
        jFormattedTextFieldStudentSearch.setText("");
        jButton1.setEnabled(true);
        jFormattedTextFieldStudentSearch.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelStudentActionPerformed

    private void jButtonEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStudentActionPerformed
        flag = 2;
        jFormattedTextFieldStudentName.setEnabled(true);
        jFormattedTextFieldStudentAddress.setEnabled(true);
        jFormattedTextFieldStudentPhone.setEnabled(true);
        jFormattedTextFieldStudentPassword.setEnabled(true);
        jFormattedTextFieldCourseID.setEnabled(true);
        jButtonSaveStudent.setEnabled(true);
        jButtonCancelStudent.setEnabled(true);
        jButtonEditStudent.setEnabled(false);
        jButtonAddStudent.setEnabled(false);
        jButtonDeleteStudent.setEnabled(false);
    }//GEN-LAST:event_jButtonEditStudentActionPerformed

    private void jButtonDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStudentActionPerformed
        int answer = 0;
        answer = JOptionPane.showConfirmDialog(rootPane, "Confirm Delete?");
        if(answer==JOptionPane.YES_OPTION) {
            st.setId(jFormattedTextFieldStudentId.getText());
            sm.DeleteStudent(st);
            jFormattedTextFieldStudentName.setText("");
            jFormattedTextFieldStudentNatio.setText("");
            jFormattedTextFieldStudentAddress.setText("");
            jFormattedTextFieldStudentPass.setText("");
            jFormattedTextFieldStudentPhone.setText("");
            jFormattedTextFieldStudentId.setText("");
            jFormattedTextFieldStudentPassword.setText("");
            jFormattedTextFieldCourseID.setText("");
            jFormattedTextFieldStudentName.setEnabled(false);
            jFormattedTextFieldStudentNatio.setEnabled(false);
            jFormattedTextFieldStudentAddress.setEnabled(false);
            jFormattedTextFieldStudentPass.setEnabled(false);
            jFormattedTextFieldStudentPhone.setEnabled(false);
            jFormattedTextFieldStudentId.setEnabled(false);
            jFormattedTextFieldCourseID.setEnabled(false);
            jButtonSaveStudent.setEnabled(false);
            jButtonAddStudent.setEnabled(true);
            jButtonCancelStudent.setEnabled(false);
            jButtonEditStudent.setEnabled(false);
            jButtonDeleteStudent.setEnabled(false);
            FillStudentTable("SELECT *FROM students ORDER BY name");
        }
    }//GEN-LAST:event_jButtonDeleteStudentActionPerformed
    
    private void jFormattedTextFieldStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldStudentSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldStudentSearchActionPerformed

    private void jFormattedTextFieldCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCourseIDActionPerformed

    private void jButtonManageLecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageLecturersActionPerformed
        EmployeeAddLecturer screen = new EmployeeAddLecturer();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManageLecturersActionPerformed

    private void jButtonManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManageStudentsActionPerformed

    private void FillStudentTable(String sql) { 
        ArrayList data = new ArrayList();
        String [] columns = new String[]{"id","name","nationality","address",
            "passport","phone","password","courseID"};
        connection.Connection();
        connection.ExecuteSQL(sql);
        try {
            connection.rs.first();
            do {
                data.add(new Object[]{connection.rs.getString("id"),
                connection.rs.getString("name"),
                connection.rs.getString("nationality"),
                connection.rs.getString("address"),
                connection.rs.getString("passport"),
                connection.rs.getString("phone"),
                connection.rs.getString("password"),
                connection.rs.getString("courseID")});
            } while(connection.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Search for another name");
        }
        StudentsTable stmodel = new StudentsTable(data, columns);
        jTableStudents.setModel(stmodel);
        jTableStudents.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableStudents.getColumnModel().getColumn(0).setResizable(false);
        jTableStudents.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableStudents.getColumnModel().getColumn(1).setResizable(false);
        jTableStudents.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTableStudents.getColumnModel().getColumn(2).setResizable(false);
        jTableStudents.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableStudents.getColumnModel().getColumn(3).setResizable(false);
        jTableStudents.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTableStudents.getColumnModel().getColumn(4).setResizable(false);
        jTableStudents.getColumnModel().getColumn(5).setPreferredWidth(130);
        jTableStudents.getColumnModel().getColumn(5).setResizable(false);
        jTableStudents.getColumnModel().getColumn(6).setPreferredWidth(70);
        jTableStudents.getColumnModel().getColumn(6).setResizable(false);
        jTableStudents.getColumnModel().getColumn(7).setPreferredWidth(60);
        jTableStudents.getColumnModel().getColumn(7).setResizable(false);
        jTableStudents.getTableHeader().setReorderingAllowed(false);
        jTableStudents.setAutoResizeMode(jTableStudents.AUTO_RESIZE_OFF);
        jTableStudents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        connection.Desconnect();
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonCancelStudent;
    private javax.swing.JButton jButtonDeleteStudent;
    private javax.swing.JButton jButtonEditStudent;
    private javax.swing.JButton jButtonManageCourses;
    private javax.swing.JButton jButtonManageLecturers;
    private javax.swing.JButton jButtonManageStudents;
    private javax.swing.JButton jButtonSaveStudent;
    private javax.swing.JFormattedTextField jFormattedTextFieldCourseID;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentAddress;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentId;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentName;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentNatio;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentPass;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentPassword;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentPhone;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentSearch;
    private javax.swing.JInternalFrame jInternalFrameCoursesAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelStudentPassport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudents;
    // End of variables declaration//GEN-END:variables
}
