/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import databasecontrol.AttendanceManager;
import databasecontrol.DatabaseConnection;
import java.util.ArrayList;
import models.Attendance;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.AttendanceTable;

/**
 *
 * @author julio
 */
public class LecturerAttendance extends javax.swing.JFrame {

    DatabaseConnection connection = new DatabaseConnection();
    Attendance att = new Attendance();
    AttendanceManager am = new AttendanceManager();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
    String date = sdf.format(new Date(System.currentTimeMillis()));
    
    /**
     * Creates new form LecturerAttendance
     */
    public LecturerAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAttendance = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButtonCreateAttendance = new javax.swing.JButton();
        jFormattedTextFieldAttendanceList = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldStudentName = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttendance = new javax.swing.JTable();
        jRadioButtonPresent = new javax.swing.JRadioButton();
        jRadioButtonLate = new javax.swing.JRadioButton();
        jRadioButtonAbsent = new javax.swing.JRadioButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldStudentID = new javax.swing.JFormattedTextField();
        jButtonTests = new javax.swing.JButton();
        jButtonAttendance = new javax.swing.JButton();
        jButtonCourses1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setVisible(true);

        jButtonCreateAttendance.setText("Attendance");
        jButtonCreateAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAttendanceActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jFormattedTextFieldStudentName.setEnabled(false);

        jTableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAttendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAttendance);

        buttonGroupAttendance.add(jRadioButtonPresent);
        jRadioButtonPresent.setText("PRESENT");

        buttonGroupAttendance.add(jRadioButtonLate);
        jRadioButtonLate.setText("LATE");

        buttonGroupAttendance.add(jRadioButtonAbsent);
        jRadioButtonAbsent.setText("ABSENT");

        jButtonUpdate.setText("Update");
        jButtonUpdate.setEnabled(false);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jFormattedTextFieldStudentID.setEnabled(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPresent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonLate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jButtonCreateAttendance)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldAttendanceList, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFormattedTextFieldStudentName))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateAttendance)
                    .addComponent(jFormattedTextFieldAttendanceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPresent)
                    .addComponent(jRadioButtonLate)
                    .addComponent(jRadioButtonAbsent)
                    .addComponent(jButtonUpdate)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(140, 60, 580, 370);

        jButtonTests.setText("Tests");
        jButtonTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTests);
        jButtonTests.setBounds(30, 400, 100, 22);

        jButtonAttendance.setText("Attendance");
        jButtonAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendanceActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAttendance);
        jButtonAttendance.setBounds(30, 280, 100, 22);

        jButtonCourses1.setText("Courses");
        jButtonCourses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourses1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCourses1);
        jButtonCourses1.setBounds(30, 170, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bglecturermainattendance.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 730, 450);

        setSize(new java.awt.Dimension(739, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTestsActionPerformed

    private void jButtonAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAttendanceActionPerformed

    private void jButtonCourses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourses1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCourses1ActionPerformed

    private void jButtonCreateAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAttendanceActionPerformed
        connection.Connection();
        
        att.setSearch(jFormattedTextFieldAttendanceList.getText());
        List<String[]> list = new ArrayList<>();
        String searchvalue = "VGC"+att.getSearch();

        connection.ExecuteSQL("SELECT *FROM students WHERE courseID='"+searchvalue+"'");
        try {
            connection.rs.first();
            do {
                list.add(new String[]{connection.rs.getString("name"),
                connection.rs.getString("id")});
            } while(connection.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Search for another value");
        }
        
        am.CreateTableAttendance(att);
        for (String[] i : list) {
            am.InsertIntoTable(att,i);
        }
        FillAttendanceTable(att);
    }//GEN-LAST:event_jButtonCreateAttendanceActionPerformed

    private void jTableAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAttendanceMouseClicked
        String id = ""+jTableAttendance.getValueAt(jTableAttendance.getSelectedRow(), 1);
        connection.Connection();
        
        String courseID = "vgc"+jFormattedTextFieldAttendanceList.getText().toLowerCase();
        String tablename = courseID + date;
        
        connection.ExecuteSQL("SELECT *FROM "+tablename+" WHERE studentid='"+id+"'");
        try {
            connection.rs.first();
            jFormattedTextFieldStudentName.setText(connection.rs.getString("studentname"));
            jFormattedTextFieldStudentID.setText(connection.rs.getString("studentid"));
            if (connection.rs.getString("attendance") == "PRESENT") {
                    jRadioButtonPresent.setSelected(true);
            } else if (connection.rs.getString("attendance") == "LATE") {
                    jRadioButtonLate.setSelected(true);
            } else if (connection.rs.getString("attendance") == "ABSENT") {
                    jRadioButtonAbsent.setSelected(true);
            }
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Selection Error:\n" + ex.getMessage());
            }
        
        jButtonUpdate.setEnabled(true);
        
        connection.Desconnect();
    }//GEN-LAST:event_jTableAttendanceMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        att.setSearch(jFormattedTextFieldAttendanceList.getText());
        att.setStudentid(jFormattedTextFieldStudentID.getText());
        if (jRadioButtonAbsent.isSelected()) {
            att.setAttendance("ABSENT");
        } else if (jRadioButtonLate.isSelected()) {
            att.setAttendance("LATE");
        } else if (jRadioButtonPresent.isSelected()) {
            att.setAttendance("PRESENT");
        }
        am.UpdateInformation(att);
        FillAttendanceTable(att);
        jButtonUpdate.setEnabled(false);
        jButtonCreateAttendance.setEnabled(true);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void FillAttendanceTable(Attendance att) {
        att.setSearch(jFormattedTextFieldAttendanceList.getText());
        String courseID = "VGC"+att.getSearch();
        String tablename = courseID + date;
        
        ArrayList data = new ArrayList();
        String [] columns = new String[]{"studentname","studentid","attendance"};
        connection.Connection();
        connection.ExecuteSQL("SELECT *FROM "+tablename+" ORDER BY studentname");
        try {
            connection.rs.first();
            do {
                data.add(new Object[]{connection.rs.getString("studentname"),
                connection.rs.getString("studentid"),
                connection.rs.getString("attendance")});
            } while(connection.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data retrieval error!");
        }
        AttendanceTable attmodel = new AttendanceTable(data, columns);
        jTableAttendance.setModel(attmodel);
        jTableAttendance.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableAttendance.getColumnModel().getColumn(1).setResizable(false);
        jTableAttendance.getColumnModel().getColumn(2).setPreferredWidth(60);
        jTableAttendance.getColumnModel().getColumn(2).setResizable(false);
        jTableAttendance.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableAttendance.getColumnModel().getColumn(3).setResizable(false);
        jTableAttendance.getTableHeader().setReorderingAllowed(false);
        jTableAttendance.setAutoResizeMode(jTableAttendance.AUTO_RESIZE_OFF);
        jTableAttendance.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        connection.Desconnect();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAttendance;
    private javax.swing.JButton jButtonAttendance;
    private javax.swing.JButton jButtonCourses1;
    private javax.swing.JButton jButtonCreateAttendance;
    private javax.swing.JButton jButtonTests;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JFormattedTextField jFormattedTextFieldAttendanceList;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentID;
    private javax.swing.JFormattedTextField jFormattedTextFieldStudentName;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonAbsent;
    private javax.swing.JRadioButton jRadioButtonLate;
    private javax.swing.JRadioButton jRadioButtonPresent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAttendance;
    // End of variables declaration//GEN-END:variables
}
