/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import databasecontrol.CourseManager;
import databasecontrol.DatabaseConnection;
import databasecontrol.StudentManager;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.Courses;
import models.Student;
import models.TestsTable;

/**
 *
 * @author julio
 */
public class StudentMain extends javax.swing.JFrame {

    DatabaseConnection connection = new DatabaseConnection();
    StudentManager sm = new StudentManager();
    CourseManager cm = new CourseManager();
    Student st = new Student();
    Courses co = new Courses();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    String date = sdf.format(new Date(System.currentTimeMillis()));
    
    /**
     * Creates new form StudentMain
     */
    public StudentMain(String userid) {
        initComponents();
        jLabel2.setText("Welcome! Today is "+date);
        connection.Connection();
        st = sm.SearchStudentById(userid);
        jLabelName.setText(st.getName());
        jLabelNationality.setText(st.getNationality());
        jLabelPassport.setText(st.getPassport());
        jLabelPhone.setText(st.getPhone());
        jLabelAddress.setText(st.getAddress());
        co = cm.searchCoursesForStudent(st, co);
        jLabelCourseID.setText(co.getId());
        jLabelCourseName.setText(co.getName());
        jLabelCourseLecturer.setText(co.getLecturer());
        jLabelCourseTimeDay.setText(co.getTime() + " " + co.getDay());
        FillTestsTable("SELECT *FROM tests WHERE testid LIKE'%" +
                co.getId() + "%'");
    }

    private StudentMain() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jLabelPassport = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTests = new javax.swing.JTable();
        jLabelCourseID = new javax.swing.JLabel();
        jLabelCourseName = new javax.swing.JLabel();
        jLabelCourseLecturer = new javax.swing.JLabel();
        jLabelCourseTimeDay = new javax.swing.JLabel();
        jButtonLOGOFF3 = new javax.swing.JButton();
        jButtonInformation = new javax.swing.JButton();
        jButtonTests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Welcome!");

        jLabelName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelName.setText("Name:");
        jLabelName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAddress.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelAddress.setText("Address:");
        jLabelAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNationality.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelNationality.setText("Nationality:");
        jLabelNationality.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPassport.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelPassport.setText("Passport:");
        jLabelPassport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPhone.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelPhone.setText("Phone:");
        jLabelPhone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTests);

        jLabelCourseID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelCourseID.setText("CourseID:");
        jLabelCourseID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCourseName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelCourseName.setText("Name:");
        jLabelCourseName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCourseLecturer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelCourseLecturer.setText("Lecturer:");
        jLabelCourseLecturer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCourseTimeDay.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelCourseTimeDay.setText("Time:");
        jLabelCourseTimeDay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelPassport, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCourseLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCourseTimeDay, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jLabelNationality))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassport)
                    .addComponent(jLabelPhone))
                .addGap(14, 14, 14)
                .addComponent(jLabelAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseID)
                    .addComponent(jLabelCourseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseLecturer)
                    .addComponent(jLabelCourseTimeDay))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 60, 560, 360);

        jButtonLOGOFF3.setText("Log Off");
        jButtonLOGOFF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGOFF3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLOGOFF3);
        jButtonLOGOFF3.setBounds(640, 10, 72, 30);

        jButtonInformation.setText("Information");
        jButtonInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformationActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInformation);
        jButtonInformation.setBounds(20, 200, 120, 22);

        jButtonTests.setText("Tests");
        jButtonTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTests);
        jButtonTests.setBounds(20, 370, 120, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgstudentmain.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -17, 760, 460);

        setSize(new java.awt.Dimension(743, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLOGOFF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGOFF3ActionPerformed
        LoginSelectionFrame screen = new LoginSelectionFrame();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLOGOFF3ActionPerformed

    private void jButtonTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTestsActionPerformed

    private void jButtonInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformationActionPerformed

    }//GEN-LAST:event_jButtonInformationActionPerformed

    private void FillTestsTable(String sql) { 
        ArrayList data = new ArrayList();
        String [] columns = new String[]{"testid","activitytype","testname","duedate",
            "percentage"};
        connection.Connection();
        connection.ExecuteSQL(sql);
        try {
            connection.rs.first();
            do {
                data.add(new Object[]{connection.rs.getString("testid"),
                connection.rs.getString("activitytype"),
                connection.rs.getString("testname"),
                connection.rs.getString("duedate"),
                connection.rs.getString("percentage")});
            } while(connection.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Search for another name");
        }
        
        TestsTable tesmodel = new TestsTable(data, columns);
        jTableTests.setModel(tesmodel);
        jTableTests.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableTests.getColumnModel().getColumn(0).setResizable(false);
        jTableTests.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableTests.getColumnModel().getColumn(1).setResizable(false);
        jTableTests.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableTests.getColumnModel().getColumn(2).setResizable(false);
        jTableTests.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableTests.getColumnModel().getColumn(3).setResizable(false);
        jTableTests.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTableTests.getColumnModel().getColumn(4).setResizable(false);
        jTableTests.getTableHeader().setReorderingAllowed(false);
        jTableTests.setAutoResizeMode(jTableTests.AUTO_RESIZE_OFF);
        jTableTests.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        connection.Desconnect();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInformation;
    private javax.swing.JButton jButtonLOGOFF;
    private javax.swing.JButton jButtonLOGOFF1;
    private javax.swing.JButton jButtonLOGOFF2;
    private javax.swing.JButton jButtonLOGOFF3;
    private javax.swing.JButton jButtonTests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCourseID;
    private javax.swing.JLabel jLabelCourseLecturer;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseTimeDay;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelPassport;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTests;
    // End of variables declaration//GEN-END:variables
}
